import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning >
            <body>
                <main className="flex flex-col min-h-screen">
                    <section className="flex-1 flex flex-col">
                        {children}
                    </section>
                </main>
                <Toaster richColors position="bottom-right" />
            </body>
        </html>
    );
}
